title: <p align="center"> Tejasvy Gunturu </p>
logo: /assets/img/profile.jpg
description:
  <p align="center">
  <a href=" /assets/Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/gunturutejasvy/">LinkedIn</a> |
  <a href="https://github.com/tejasvygunturu">GitHub</a>
  
  <br>   
  I'm Pursuing Masters of Science on ML and AI course from Liverpool John Moores University and PG from IIIT Bengaluru
  Working in Accenture on SAP SD domain for 1.3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
